from addons.string_utils import StringUtils
from distutils.util import strtobool
from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from src.testproject.sdk.drivers.actions import Actions
from subtests import test_assign_an_officer_to_first_dispatch
from subtests import test_create_a_new_dispatch_in_dispatch_center
from subtests import test_dispatch_put_all_officers_onduty
from subtests import test_login_vsoc_open_dispatch_center
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Hans' Project
    Package: TestProject.Generated.Tests.HansProject
    Test: TC0001 - Dispatch Escalate to IR with only one assignee, IR default assignee should be dispatch assignee, IR default site should be dispatch site
    Generated by: Hans Hwang (hhwang@d3security.com)
    Generated on 10/02/2021, 00:09:41
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="BaBKSvR0DJRxUgabYl9EV9571aulikOb6rRn4RtuuX8",
                              project_name="Hans' Project",
                              job_name="TC0001 - Dispatch Escalate to IR with only one assignee, IR default assignee should be dispatch assignee, IR default site should be dispatch site")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://gsstage.d3securityonline.com/QA/VSOC/Login.aspx"
    Username = "hans"
    Password = "D1sney2020!"
    IRtitle = "TC0001 - Dispatch Escalate to IR with only one assignee, IR default assignee should be dispatch assignee, IR default site should be dispatch site"
    CurrentSite = ""
    AssignedFirstOfficerName = ""
    DispatchIDtype = ""
    DispatchID = ""
    AssigneeFirstName = ""
    AssigneeLastName = ""
    AssigneeNameAfterSave = ""
    AssigneeLastName2 = ""

    '''
    # (STEP DISABLED)
    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')
    '''

    # 2. Run Login VSOC - Open Dispatch Center
    test_login_vsoc_open_dispatch_center.test_main(driver)

    # 3. Click top-right sub window "+ Create New"
    # This step was auto generated from several steps
    step_settings = StepSettings(always_pass=True)
    with DriverStepSettings(driver, step_settings):
        test_create_a_new_dispatch_in_dispatch_center.test_main(driver)

    # 4. Dispatch Operations Center
    # This step was auto generated from several steps
    step_settings = StepSettings(always_pass=True)
    with DriverStepSettings(driver, step_settings):
        test_dispatch_put_all_officers_onduty.test_main(driver)

    # 5. Dispatch Operations Center
    test_assign_an_officer_to_first_dispatch.test_main(driver)

    # 6. Get text from 'Corporate1'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    corporate1 = driver.find_element(By.XPATH,
                                     "//div[3]/div[2]/span/span/span[1]")
    step_output = corporate1.get_attribute("value")
    CurrentSite = step_output

    # 7. Click 'Selected Dispatch'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    selected_dispatch = driver.find_element(By.XPATH,
                                            "//a[3][. = 'Selected Dispatch']")
    selected_dispatch.click()

    # 8. Is 'Assigned Officers (1)' visible?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    assigned_officers_1_ = driver.find_element(By.XPATH,
                                               "//div[3]/div[2]/div[1]/div[1]")
    assert assigned_officers_1_.is_displayed()

    # 9. Get text from 'First assigned officer - Deepti Gupta_StgQA'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    first_assigned_officer_deepti_gupta_stgqa = driver.find_element(By.XPATH,
                                                                    "//div[3]/div[2]/div[3]/table/tbody/tr[1]/td[3]")
    step_output = first_assigned_officer_deepti_gupta_stgqa.get_attribute(
        "value")
    AssignedFirstOfficerName = step_output

    # 10. Click 'Escalate to IR'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    escalate_to_ir = driver.find_element(By.CSS_SELECTOR,
                                         "#dsp_toolbar_toIR")
    escalate_to_ir.click()

    # 11. Is 'Incident Type *' visible?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    incident_type_asterisk_ = driver.find_element(By.XPATH,
                                                  "//div/div/div/div[. = 'Incident Type *']")
    assert incident_type_asterisk_.is_displayed()

    # 12. Click 'SPAN3'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    span3 = driver.find_element(By.XPATH,
                                "//div[2]/div/div/div[1]/div/div/table/tbody/tr/td/div[1]/table/tbody/tr[1]/td/div/div/div/div[2]/span/span/span[1]")
    span3.click()

    # 13. Click 'Administrative1'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    administrative1 = driver.find_element(By.XPATH,
                                          "//li[3][. = 'Administrative']")
    administrative1.click()

    # 14. Click 'Title'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    title = driver.find_element(By.CSS_SELECTOR,
                                "[name=' Title']")
    title.click()

    # 15. Type '{IRtitle}' in 'Title'
    step_settings = StepSettings(timeout=35000)
    with DriverStepSettings(driver, step_settings):
        # Step switches frame driver context.
        driver.switch_to.default_content()
        driver.switch_to.frame(
            driver.find_element(By.XPATH,
                                "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
        title = driver.find_element(By.CSS_SELECTOR,
                                    "[name=' Title']")
        title.send_keys(f'{IRtitle}')

    '''
    # (STEP DISABLED)
    # 16. Does 'Gupta_StgQA, Deepti' contain 'Gupta_StgQA, Deepti'?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
    driver.find_element(By.XPATH,
    "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    gupta_stgqa_deepti = driver.find_element(By.XPATH,
    "//span/span/span[. = 'Gupta_StgQA, Deepti']")
    step_output = gupta_stgqa_deepti.text
    assert step_output and ("Gupta_StgQA, Deepti" in step_output)
    '''

    '''
    # (STEP DISABLED)
    # 17. Does 'Corporate' contain 'Corporate'?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
    driver.find_element(By.XPATH,
    "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    corporate = driver.find_element(By.XPATH,
    "//tr[4]/td[1]/div/div/div/div[2]/span/span/span[. = 'Corporate']")
    step_output = corporate.text
    assert step_output and ("Corporate" in step_output)
    '''

    # 18. Click 'Escalate'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    escalate = driver.find_element(By.CSS_SELECTOR,
                                   "#escalate")
    escalate.click()

    # 19. Pause for '3000'ms
    driver.pause(milliseconds=3000)

    # 20. Switch to window '2'
    driver.switch_to.window(driver.window_handles[2])

    # 21. Does 'General Information' contain 'General Information'?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "/html/body/form/div[3]/div[1]/div[4]/iframe"))
    general_information = driver.find_element(By.XPATH,
                                              "//div[. = 'General Information']")
    step_output = general_information.text
    assert step_output and ("General Information" in step_output)

    # 22. Does 'Assigned To Label' contain '{CurrentSite}'?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "/html/body/form/div[3]/div[1]/div[4]/iframe"))
    assigned_to_label = driver.find_element(By.CSS_SELECTOR,
                                            "#irView_AssignedToLabel")
    step_output = assigned_to_label.text
    assert step_output and (f'{CurrentSite}' in step_output)

    # 23. Get text from 'Assigned To Label'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "/html/body/form/div[3]/div[1]/div[4]/iframe"))
    assigned_to_label = driver.find_element(By.CSS_SELECTOR,
                                            "#irView_AssignedToLabel")
    step_output = assigned_to_label.get_attribute("value")
    AssigneeNameAfterSave = step_output

    # 24. Splits '{AssigneeNameAfterSave}' around matches of given regular expression '/([^,]+)/g' limited by '2'
    step_output = driver.addons().execute(
        StringUtils.splitstringwithregex(
            sourceString=f'{AssigneeNameAfterSave}',
            regex="/([^,]+)/g",
            limit=2,
            indexOfElement="0"))
    AssigneeLastName = step_output

    # 25. Splits '{AssigneeNameAfterSave}' around matches of given regular expression '/([^,]+)/g' limited by '2'
    step_output = driver.addons().execute(
        StringUtils.splitstringwithregex(
            sourceString=f'{AssigneeNameAfterSave}',
            regex="/([^,]+)/g",
            limit=2,
            indexOfElement="1"))
    AssigneeFirstName = step_output

    # 26. Is '{AssignedFirstOfficerName}' contains '{AssigneeFirstName}'?
    step_output = driver.addons().execute(
        StringUtils.stringcontains(
            inputString=f'{AssignedFirstOfficerName}',
            substring=f'{AssigneeFirstName}',
            caseSensitive=bool(strtobool(Yes)),
            expectedResult="true"))

    '''
    # (STEP DISABLED)
    # 27. Splits '{AssigneeLastName}' around matches of given regular expression '/([^\)]+)/g' limited by '2'
    step_output = driver.addons().execute(
    StringUtils.splitstringwithregex(
    sourceString = f'{AssigneeLastName}',
    regex = "/([^\\)]+)/g",
    limit = 2,
    indexOfElement = "1"))
    AssigneeLastName2 = step_output
    '''

    '''
    # (STEP DISABLED)
    # 28. Does 'Assigned To Label' contain '{AssigneeFirstName}'?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
    driver.find_element(By.XPATH,
    "/html/body/form/div[3]/div[1]/div[4]/iframe"))
    assigned_to_label = driver.find_element(By.CSS_SELECTOR,
    "#irView_AssignedToLabel")
    step_output = assigned_to_label.text
    assert step_output and (f'{AssigneeFirstName}' in step_output)
    '''

    '''
    # (STEP DISABLED)
    # 29. Does 'Assigned To Label' contain '{AssigneeLastName}'?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
    driver.find_element(By.XPATH,
    "/html/body/form/div[3]/div[1]/div[4]/iframe"))
    assigned_to_label = driver.find_element(By.CSS_SELECTOR,
    "#irView_AssignedToLabel")
    step_output = assigned_to_label.text
    assert step_output and (f'{AssigneeLastName}' in step_output)
    '''

    # 30. Close window with index '2'
    driver.close()

    # 31. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 32. Close window with index '1'
    driver.close()

    # 33. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    '''
    # (STEP DISABLED)
    # 34. Type '{AssigneeLastName}' in 'PersonName'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
    driver.find_element(By.XPATH,
    "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    personname = driver.find_element(By.CSS_SELECTOR,
    "[name=' PersonName']")
    personname.send_keys(f'{AssigneeLastName}')
    '''
