from addons.string_utils import StringUtils
from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors
from src.testproject.sdk.drivers.actions import Actions


"""
This pytest test was automatically generated by TestProject
    Project: Hans' Project
    Package: TestProject.Generated.Tests.HansProject
    Test: Create a new dispatch in dispatch center
    Generated by: Hans Hwang (hhwang@d3security.com)
    Generated on 10/02/2021, 00:09:41
"""


@report_assertion_errors
def test_main(driver):
    """Click top-right sub window \"+ Create New\"."""
    # Test Parameters
    DispatchIDtype = ""
    DispatchID = ""
    # Auto generated application URL parameter
    ApplicationURL = "https://gsstage.d3securityonline.com/QA/VSOC/Login.aspx"

    # 1. Does 'Active Dispatches (691)' contain 'Active Dispatches'?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    active_dispatches_691_ = driver.find_element(By.XPATH,
                                                 "//div[1]/div[1]/div[1]/div[2]/div[1]/div[1]")
    step_output = active_dispatches_691_.text
    assert step_output and ("Active Dispatches" in step_output)

    # 2. Click 'New Dispatch IMG1'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    new_dispatch_img1 = driver.find_element(By.XPATH,
                                            "//div[2]/img")
    new_dispatch_img1.click()

    # 3. Click 'Select a Dispatch Type'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    select_a_dispatch_type = driver.find_element(By.XPATH,
                                                 "//span/span/span[. = 'Select a Dispatch Type']")
    select_a_dispatch_type.click()

    # 4. Click 'Administrative'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    administrative = driver.find_element(By.XPATH,
                                         "//li[. = 'Administrative']")
    administrative.click()

    # 5. Pause for '2000'ms
    driver.pause(milliseconds=2000)

    # 6. Click 'Save2'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    save2 = driver.find_element(By.CSS_SELECTOR,
                                "#dsp_toolbar_saveNew")
    save2.click()

    # 7. Pause for '2000'ms
    driver.pause(milliseconds=2000)

    # 8. Is 'Dispatch ID - 1728 - Administrative' visible?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    dispatch_id_1728_administrative = driver.find_element(By.XPATH,
                                                          "//body/div[1]/div/div/div[1]")
    assert dispatch_id_1728_administrative.is_displayed()

    # 9. Get text from 'Dispatch ID - 1728 - Administrative'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    dispatch_id_1728_administrative = driver.find_element(By.XPATH,
                                                          "//body/div[1]/div/div/div[1]")
    step_output = dispatch_id_1728_administrative.get_attribute("value")
    DispatchIDtype = step_output

    # 10. Get substring of '{DispatchIDtype}' from '0' to '3'
    step_output = driver.addons().execute(
        StringUtils.getstringsubstring(
            beginIndex=0,
            endIndex=3,
            inputString=f'{DispatchIDtype}'))
    DispatchID = step_output

    # 11. Does 'Dispatch center list first row ID - 1728' contain '{DispatchID}'?
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'FrameOnLifeServer']|//*[@name = 'FrameOnLifeServer']|/html/body/form/iframe"))
    dispatch_center_list_first_row_id_1728 = driver.find_element(By.XPATH,
                                                                 "//div[1]/div[1]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[1]")
    step_output = dispatch_center_list_first_row_id_1728.text
    assert step_output and (f'{DispatchID}' in step_output)
